name: fithouse
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.6+7

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  pdf: ^3.10.0
  printing: ^5.11.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  android_intent_plus: ^5.3.1
  permission_handler: ^11.3.0
  dio: ^5.9.0
  http: ^1.5.0
  provider: ^6.0.5
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  video_player: ^2.7.0
  firebase_auth: ^5.7.0
  firebase_core: ^3.15.2
  image_picker: ^1.0.4
  shared_preferences: ^2.5.3
  url_launcher: ^6.2.6
  json_annotation: ^4.9.0
  google_fonts: ^6.1.0
  package_info_plus: ^8.0.0
  table_calendar: ^3.0.9
  share_plus: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/splash_logo.png"

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/json/allparkdata.json
    - assets/json/allfacilitydata.json
    - assets/json/optimized_park_data.json
    - assets/json/korea_with_grid.json
    - assets/images/splash_logo.png
    - assets/videos/flower.mp4
    - assets/images/level1.png
    - assets/images/level2.png
    - assets/images/level3.png
    - assets/images/level4.png
    - assets/images/question.png
    - assets/docs/privacy_ko.md
    - assets/docs/terms_ko.md
    # 폰트 파일이 assets/fonts 폴더에 있는지 꼭 확인하세요!

  fonts:
    # 1. 한글용 (기본 폰트)
    - family: NanumGothic
      fonts:
        - asset: assets/fonts/NanumGothic.ttf
        - asset: assets/fonts/NanumGothicExtraBold.ttf
          weight: 800
        - asset: assets/fonts/PyeojinGothic-Medium.ttf
          weight: 500
        - asset: assets/fonts/NanumGothicLight.ttf
          weight: 300
        - asset: assets/fonts/NanumGothicBold.ttf
          weight: 700
        - asset: assets/fonts/NanumGothicExtraBold.ttf
          weight: 800

    # 2. 로고용 (영어 폰트)
    - family: PyeojinGothic
      fonts:
        - asset: assets/fonts/PyeojinGothic-Regular.ttf
          weight: 400
        # 만약 PyeojinGothic의 다른 굵기 파일도 있다면 아래에 추가하세요